--[[
  ____                                  _                      _    _       _     
 |  _ \            /\                  | |                    | |  | |     | |    
 | |_) |_   _     /  \   _ __ __ _  ___| |_ _ __   __ _ _ __  | |__| |_   _| |__  
 |  _ <| | | |   / /\ \ | '__/ _` |/ _ \ __| '_ \ / _` | '__| |  __  | | | | '_ \ 
 | |_) | |_| |  / ____ \| | | (_| |  __/ |_| | | | (_| | |    | |  | | |_| | |_) |
 |____/ \__, | /_/    \_\_|  \__, |\___|\__|_| |_|\__,_|_|    |_|  |_|\__,_|_.__/ 
         __/ |                __/ |                                               
        |___/                |___/                                                
]]


local a=game.Players.LocalPlayer;local b=a.Character;local c=require(game:GetService("ReplicatedStorage").Modules.inventoryController)local d=require(game:GetService("ReplicatedStorage").Modules.statModule)local e=require(game:GetService("ReplicatedStorage").Modules.pickaxesModule)local f={"Starter Egg","Spotted Egg","Floral Egg","Desert Egg","Snow Egg","Cave Egg","Ocean Egg","Jungle Egg","Volcano Egg","Space Egg","Undead Egg","Heavenly Egg","Devil Egg","Fossil Egg","Tentacle Egg","1M Visits Egg","Exclusive Egg 1"}local g=loadstring(game:HttpGet("https://raw.githubusercontent.com/ArgetnarYT/Library/main/ArgetnarLibrary.lua"))()local h=g:Window("Argetnar Hub")g:Notify("Script","Loading......")local i=h:Tab("Main")i:Toggle("Auto Clicker",function(j)_G.toggleClick=j;while _G.toggleClick do task.wait()if _G.toggleClick then b:FindFirstChildWhichIsA("Tool"):Activate()game:GetService("ReplicatedStorage").Remotes.Click:InvokeServer()end end end)local k=h:Tab("Pets")k:Toggle("Auto Purchase Eggs",function(j)_G.toggleAutoBuyEgg=j;while _G.toggleAutoBuyEgg do task.wait(0.1)if _G.toggleAutoBuyEgg then game:GetService("ReplicatedStorage").Remotes.buyEgg:InvokeServer(_G.SelectedPet,1)end end end)k:Dropdown("Egg List",f,function(l)_G.SelectedPet=l end)k:Toggle("Auto Equip Best Pets",function(j)_G.equipBest=j;while _G.equipBest do task.wait(1)if _G.equipBest then c.equipBest()end end end)i:Toggle("Auto Claim Achievements",function(j)_G.autoAchievements=j;while _G.autoAchievements do task.wait(1)if _G.autoAchievements then for m,n in pairs(a.PlayerGui.rewards.achievementsPanel.RebirthCounter.scrollingFrame:GetChildren())do if n:IsA("Frame")then game:GetService("ReplicatedStorage").Remotes.claimAchievment:FireServer(n.Name)end end end end end)k:Toggle("Auto Rebirth",function(j)_G.autoRebirth=j;while _G.autoRebirth do task.wait(1)if _G.autoRebirth then game:GetService("ReplicatedStorage").Remotes.Rebirth:FireServer()end end end)k:Toggle("Auto Buy Pickaxes",function(j)_G.autoBuyPick=j;while _G.autoBuyPick do task.wait(1)if _G.autoBuyPick then for m,o in pairs(e.picks)do game:GetService("ReplicatedStorage").Remotes.BuyPickaxe:InvokeServer(m)end end end end)local p=h:Tab("Misc")p:Button("Rejoin",function()local q=game:GetService("TeleportService")local r=game:GetService("Players").LocalPlayer;q:TeleportToPlaceInstance(game.PlaceId,game.JobId,r)end)p:Slider("Walk Speed",16,500,50,function(s)game.Players.LocalPlayer.Character.Humanoid.WalkSpeed=s end)p:Button("Destroy",function()game.CoreGui.MangoHub:Destroy()end)local t=h:Tab("Credits")t:Label("Hub by Argetnar & Doku & Brinen")local u=t:Label("v2.8")g:Notify("Script","Was Loaded!")
